<template>
  <div style="width: 100%; display: flex; justify-content: center">
    <div class="img-box">
      <img
        class="itme-img"
        src="@/assets/images/energyAssets.png"
        width="180"
        height="180"
      />
      <img
        class="itme-img"
        src="@/assets/images/inde-bg.jpg"
        width="180"
        height="180"
      />
      <img
        class="itme-img"
        src="@/assets/images/equipment.png"
        width="180"
        height="180"
      />
      <img
        class="itme-img"
        src="@/assets/images/login-background.jpg"
        width="180"
        height="180"
      />
      <img
        class="itme-img"
        src="@/assets/images/officeAsstes.png"
        width="180"
        height="180"
      />
      <img
        class="itme-img"
        src="@/assets/images/pay.png"
        width="180"
        height="180"
      />
      <img
        class="itme-img"
        src="@/assets/images/zj-login-form-bg.png"
        width="180"
        height="180"
      />
      <img
        class="itme-img"
        src="@/assets/images/zj-login-form-bg1.png"
        width="180"
        height="180"
      />
      <img
        class="itme-img"
        src="@/assets/images/zj-login-bg1.png"
        width="180"
        height="180"
      />
    </div>
  </div>
</template>
